### ISSUE TITLE
AWS S3 signed URL generation

### ISSUE THREAD

**Issue by imprakharshukla** [architect/aws-lite.org#10]
Hey! I was trying out this library but couldn't find any documentation to generate signed url for an object in the bucket.
The v3 sdk handles it the following way:
    import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
    
    
    const s3Configuration: S3ClientConfig = {
        credentials: {
            accessKeyId: '<ACCESS_KEY_ID>',
            secretAccessKey: '<SECRET_ACCESS_KEY>'
        },
        region: '<REGION>',
    };
    const s3 = new S3Client(s3Configuration);
    const command = new GetObjectCommand({Bucket: '<BUCKET>', Key: '<KEY>' });
    const url = await getSignedUrl(s3, command, { expiresIn: 15 * 60 }); // expires in seconds
    
  Am I missing anything or is it not yet implemented? Thank you.

**Comment by ryanblock** [comment]
Not yet implemented, but def something we should do. Please feel free to open an enhancement (and PR, even!) over at https://github.com/architect/aws-lite 💕
